import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";

const notoSans = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${notoSans.className} antialiased h-screen flex flex-col`}
      >
        <Header />
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
