import { AuthProvider } from "@/components/AuthProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./_components/Header";
import "./globals.css";

const pretendard = localFont({
  src: "../font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});
// const notoSans = Noto_Sans_KR({
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      suppressHydrationWarning
      className={`${pretendard.variable}`}
    >
      <body
        className={`${pretendard.className} antialiased h-screen flex flex-col`}
      >
        <AuthProvider>
          <Header />
          <div className="flex-1">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
