name: Deploy to EC2

on:
  push:
    branches:
      - dev

concurrency:
  group: deploy-to-ec2
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 프로젝트 폴더가 있으면 백업
            mv piece-admin piece-admin-backup || true

            # 새 버전 클론
            git clone -b dev --single-branch https://singrum2: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@github.com/singrum2/piece-admin.git

            # 환경 변수 설정
            cp config/.env piece-admin/.env

            # 새 프로젝트 디렉토리로 이동
            cd piece-admin

            # 의존성 설치 및 빌드
            npm install
            npm run build

            # 프로세스 빠르게 재시작
            pm2 startOrReload ecosystem.config.js --only next-app || pm2 restart next-app || pm2 start npm --name "next-app" -- start

            # pm2 상태 저장
            pm2 save

            # 백업 삭제 (빌드 성공 이후)
            rm -rf ../piece-admin-backup
